"use strict";

const bi = (en, zh) => ({ en, zh });

window.PHISHWISE_CONTENT = Object.freeze({
  topics: [
    { id: "sender", lesson: "sender", name: bi("Sender identity", "发件人身份") },
    { id: "domain", lesson: "links", name: bi("Domains and subdomains", "域名与子域名") },
    { id: "https", lesson: "links", name: bi("HTTPS limitations", "HTTPS 的局限") },
    { id: "social", lesson: "psychology", name: bi("Social engineering", "社会工程心理") },
    { id: "attachment", lesson: "attachments", name: bi("Suspicious attachments", "可疑附件") },
    { id: "login", lesson: "login", name: bi("Fake login pages", "虚假登录页面") },
    { id: "mfa", lesson: "login", name: bi("MFA role and limits", "MFA 的作用与局限") },
    { id: "click", lesson: "incident", name: bi("Response after clicking", "点击后的响应") },
    { id: "credential", lesson: "incident", name: bi("Response after credential entry", "输入凭据后的响应") },
    { id: "verify", lesson: "incident", name: bi("Independent verification and reporting", "独立核实与报告") },
  ],

  objectiveMap: [
    {
      title: bi("Identity and destination evidence", "身份与目标地址证据"),
      outcome: bi("Distinguish display names, From and Reply-To addresses, controlling domains, and the limited meaning of HTTPS.", "区分显示名称、From 与 Reply-To 地址、控制域名，并理解 HTTPS 能证明和不能证明的内容。"),
      evidence: bi("Pre/post topics 1–3 plus sender and destination clues in all three inspection scenarios.", "前后测主题 1 至 3，以及三个检查场景中的发件人和目标地址信号。"),
      limitation: bi("One test item is an indicator for each topic, not proof of complete mastery.", "每个主题的一道测试题只能作为表现指标，不能证明完全掌握。"),
    },
    {
      title: bi("Attack reasoning", "攻击推理"),
      outcome: bi("Explain how pressure, impersonation, attachments, and fake login pages advance an attacker's objective.", "解释施压、身份冒充、附件和虚假登录页面怎样推进攻击者目的。"),
      evidence: bi("Eight lessons and the five-part explanation shown for every inspection clue.", "八个学习主题，以及每个检查信号显示的五部分解释。"),
      limitation: bi("Clicking a clue measures recognition; participant explanation is needed to assess deeper reasoning.", "点击信号主要测量识别能力，更深入的推理仍需要参与者解释自己的判断。"),
    },
    {
      title: bi("Safe individual response", "个人安全响应"),
      outcome: bi("Choose proportionate actions before interaction and after a click, credential entry, MFA approval, or attachment execution.", "在交互前以及点击、输入凭据、批准 MFA 或打开附件后选择适当响应。"),
      evidence: bi("Pre/post topics 8–10 and first-attempt answers across seven defence decisions.", "前后测主题 8 至 10，以及七个防御情境的首次作答。"),
      limitation: bi("Immediate feedback supports learning, so formal evaluation must preserve the first attempt separately from later practice.", "即时反馈用于促进学习，因此正式评价必须把首次作答与后续练习分开保存。"),
    },
    {
      title: bi("Supporting security controls", "辅助安全控制"),
      outcome: bi("Relate learner checks and reporting to prevention, detection, response, and recovery controls.", "把学习者的检查和报告操作与预防、发现、响应和恢复控制联系起来。"),
      evidence: bi("Layered-control lesson, organisation-wide campaign decision, and security-engineering risk cases.", "分层控制课程、组织范围攻击情境和安全工程风险案例。"),
      limitation: bi("The website teaches the model; a participant discussion or follow-up question is needed to measure system-level understanding.", "网页负责教授模型，系统层面的理解还需要通过参与者讨论或补充问题测量。"),
    },
    {
      title: bi("Expected evaluation result", "预期评价结果"),
      outcome: bi("Use paired first-attempt evidence to test whether post-test performance is higher than pre-test performance.", "使用配对的首次作答证据，检验后测表现是否高于前测表现。"),
      evidence: bi("Pre/post totals, item outcomes, inspection first attempts, defence first attempts, and anonymous feedback.", "前后测总分、题目结果、检查首次得分、防御首次作答和匿名反馈。"),
      limitation: bi("A working website and a score increase do not establish effectiveness until real consenting participants are tested.", "网站能够运行和分数提高都不能单独证明教学有效，仍需真实且自愿的参与者测试。"),
    },
  ],

  engineeringRisks: [
    {
      id: "credential",
      title: bi("Credential and session capture", "凭据与会话窃取"),
      asset: bi("University account, authenticated session, learning access, and data available through that identity.", "大学账户、认证会话、学习权限，以及该身份能够访问的数据。"),
      attackPath: bi("Impersonated message → deceptive domain → copied login page → password, MFA, or session capture → account abuse.", "冒充邮件 → 欺骗性域名 → 复制登录页面 → 窃取密码、MFA 或会话 → 滥用账户。"),
      controls: bi("Prevent with domain protection and phishing-resistant authentication; detect unusual sessions; respond by revoking access; recover the account through a known service.", "通过域名保护和抗钓鱼认证进行预防；发现异常会话；撤销访问进行响应；通过已知服务恢复账户。"),
      residual: bi("A compromised official account or stolen live session may still appear trusted after several controls succeed.", "被入侵的官方账户或被窃取的活动会话，在多项控制正常工作后仍可能显得可信。"),
      tradeoff: bi("Stronger authentication and shorter sessions reduce exposure but can increase login and account-recovery effort.", "更强认证和更短会话可以降低暴露，但会增加登录和账户恢复负担。"),
    },
    {
      id: "attachment",
      title: bi("Malicious attachment execution", "恶意附件执行"),
      asset: bi("Student device, local files, university credentials, and connected services.", "学生设备、本地文件、大学凭据和已连接服务。"),
      attackPath: bi("Trusted context → disguised attachment or archive → user opens content → code or credential page runs → device or account exposure.", "可信情境 → 伪装附件或压缩包 → 用户打开内容 → 代码或凭据页面运行 → 设备或账户暴露。"),
      controls: bi("Prevent with file-type policy and safe sharing; detect with sandbox and endpoint monitoring; respond through isolation; recover from a known-clean state.", "通过文件类型政策和安全共享进行预防；使用沙箱和终端监控进行发现；通过隔离进行响应；从已知干净状态恢复。"),
      residual: bi("Password-protected archives, new file formats, and user-approved execution can reduce filter visibility.", "受密码保护的压缩包、新文件格式和用户批准执行都可能降低过滤器可见性。"),
      tradeoff: bi("Blocking broad file categories reduces attack paths but may interrupt legitimate coursework and research exchange.", "阻止大量文件类型可以减少攻击路径，但也可能影响正常课程和研究资料交换。"),
    },
    {
      id: "identity",
      title: bi("Identity and financial-data collection", "身份与财务资料收集"),
      asset: bi("Student number, identity documents, bank details, privacy, and financial wellbeing.", "学号、身份证件、银行资料、隐私和财务安全。"),
      attackPath: bi("Reward or refund lure → trusted office impersonation → excessive form request → identity or payment fraud.", "奖励或退款诱饵 → 冒充可信部门 → 过度表单请求 → 身份或支付欺诈。"),
      controls: bi("Prevent through data minimisation and authenticated portals; detect unusual claims; respond by reporting exposure; recover through finance and identity-support processes.", "通过数据最小化和认证门户进行预防；发现异常申领；报告暴露进行响应；通过财务和身份支持流程恢复。"),
      residual: bi("A genuine process may request some sensitive data, so users need a trusted way to confirm purpose and minimum necessity.", "真实流程也可能要求部分敏感资料，因此用户需要可信渠道确认用途和最低必要范围。"),
      tradeoff: bi("More verification protects students but can delay legitimate refunds and increase support workload.", "更多核实能够保护学生，但可能延迟正常退款并增加支持工作量。"),
    },
    {
      id: "compromised",
      title: bi("Compromised trusted account", "可信账户被入侵"),
      asset: bi("The account owner's identity, contacts, mailbox history, and the trust of later recipients.", "账户所有者身份、联系人、邮箱历史和后续收件人的信任。"),
      attackPath: bi("Initial compromise → attacker studies real conversations → sends a contextual request from the correct domain → targets more users.", "初次入侵 → 攻击者研究真实对话 → 从正确域名发送符合情境的请求 → 攻击更多用户。"),
      controls: bi("Detect unusual rules, sessions, and sending patterns; contain by revoking tokens and searching related messages; recover the account and notify affected users.", "发现异常规则、会话和发送模式；通过撤销令牌和搜索相关邮件进行遏制；恢复账户并通知受影响用户。"),
      residual: bi("Sender and domain checks can both appear correct, so context, request, and independent verification remain necessary.", "发件人和域名检查都可能看起来正确，因此仍需检查上下文、请求内容并独立核实。"),
      tradeoff: bi("Aggressive anomaly detection finds abuse earlier but may interrupt legitimate travel, new devices, or unusual academic work.", "严格的异常检测可以更早发现滥用，但也可能干扰正常旅行、新设备或特殊学术工作。"),
    },
    {
      id: "campaign",
      title: bi("Organisation-wide campaign", "组织范围攻击"),
      asset: bi("Many user accounts, support capacity, institutional reputation, and continuity of university services.", "大量用户账户、支持能力、机构声誉和大学服务连续性。"),
      attackPath: bi("Repeated delivery → some messages bypass filters → mixed user interaction → exposed accounts spread the campaign.", "重复投递 → 部分邮件绕过过滤 → 用户产生不同交互 → 暴露账户继续传播攻击。"),
      controls: bi("Combine filtering, user reports, campaign search, indicator blocking, session revocation, communication, and recovery.", "组合过滤、用户报告、攻击搜索、指标阻止、会话撤销、沟通和恢复。"),
      residual: bi("Broad controls can miss variants while broad deletion can remove legitimate mail and evidence.", "范围过窄的控制可能漏掉变体，范围过大的删除又可能移除合法邮件和证据。"),
      tradeoff: bi("Containment speed must be balanced with evidence preservation, false positives, and clear communication.", "遏制速度需要与证据保留、误报和清晰沟通保持平衡。"),
    },
  ],

  clueLimits: {
    subject: bi("Urgency, confidentiality, rewards, and familiar context can be legitimate. Combine the subject with identity, destination, request, and workflow evidence.", "紧迫、保密、奖励和熟悉情境也可能真实存在。应把主题与身份、目标地址、请求内容和正常流程证据结合。"),
    senderName: bi("A display name is easy to copy, but a familiar name alone does not prove either safety or malicious intent.", "显示名称容易复制，但熟悉名称本身既不能证明安全，也不能证明恶意。"),
    senderEmail: bi("An unfamiliar external domain may belong to a legitimate supplier, while a compromised official account may use the correct domain.", "陌生外部域名可能属于正常供应商，被入侵的官方账户也可能使用正确域名。"),
    replyTo: bi("A different Reply-To can support legitimate ticketing or mailing systems. It becomes stronger evidence when it conflicts with the request and normal workflow.", "不同的 Reply-To 可能用于正常工单或邮件系统。当它与请求内容和正常流程冲突时，证据才更强。"),
    body: bi("Unusual requests need context. Requests for passwords or live MFA codes are especially serious, but users should still report rather than investigate the sender themselves.", "异常请求需要结合上下文。索要密码或实时 MFA 验证码尤其严重，但用户仍应报告，而不是自行调查发件人。"),
    link: bi("Link text is weak evidence because the sender controls it. Even an expected label should be checked against an independently known service.", "链接文字由发件人控制，因此属于较弱证据。即使文字符合预期，也应与独立已知服务比较。"),
    destination: bi("A mismatched controlling domain is strong evidence, but an official service can also be compromised. Domain, context, and requested action should be assessed together.", "控制域名不匹配属于较强证据，但官方服务也可能被入侵。域名、上下文和请求操作应一起判断。"),
    attachment: bi("An archive or web file is not automatically malicious. Unexpected delivery, final file type, workflow bypass, and execution behaviour determine the risk.", "压缩包或网页文件并不自动代表恶意。意外投递、最终文件类型、绕过流程和执行行为共同决定风险。"),
  },

  pretest: [
    {
      id: "pre1", topic: "sender",
      question: bi("An email displays “Southbank IT Desk”. Which check gives the strongest evidence about who sent it?", "一封邮件显示名称为“Southbank IT 服务台”。哪项检查最能说明真正的发件人？"),
      options: [
        bi("Compare the logo and signature with an older email", "将徽标和签名与旧邮件比较"),
        bi("Open the sender details and inspect the full From address and Reply-To domain", "展开发件人详情，检查完整发件地址和 Reply-To 域名"),
        bi("Check whether the display name contains the university name", "检查显示名称是否包含大学名称"),
        bi("Reply and see whether the sender answers professionally", "回复邮件，观察对方是否专业回应"),
      ], answer: 1,
    },
    {
      id: "pre2", topic: "domain",
      question: bi("Which URL is actually within the fictional domain southbank.example?", "以下哪个 URL 真正位于虚构域名 southbank.example 之下？"),
      options: [
        bi("https://southbank.example.login-check.test", "https://southbank.example.login-check.test"),
        bi("https://southbank-example.test", "https://southbank-example.test"),
        bi("https://login.southbank.example", "https://login.southbank.example"),
        bi("https://southbank.example-secure.test", "https://southbank.example-secure.test"),
      ], answer: 2,
    },
    {
      id: "pre3", topic: "https",
      question: bi("A sign-in page shows HTTPS and a padlock. What can you safely conclude?", "登录页面显示 HTTPS 和锁形图标。可以安全得出什么结论？"),
      options: [
        bi("The connection to that site is encrypted, but the site may still be operated by an attacker", "与该网站的连接已加密，但网站仍可能由攻击者运营"),
        bi("The organisation named on the page owns the site", "页面上显示的组织拥有该网站"),
        bi("A browser has checked that the login form is genuine", "浏览器已经确认登录表单真实"),
        bi("Credentials entered there cannot be intercepted or stolen", "在该页面输入的凭据不可能被截获或窃取"),
      ], answer: 0,
    },
    {
      id: "pre4", topic: "social",
      question: bi("A message signed by the “Dean” threatens enrolment cancellation within 30 minutes. What is the best interpretation?", "一封署名“院长”的邮件威胁称，30 分钟内不操作就取消注册。最佳判断是什么？"),
      options: [
        bi("Authority makes the request more likely to be legitimate", "权威身份使请求更可能是真实的"),
        bi("The short deadline means the sender probably needs a quick reply", "期限很短，说明发件人可能确实需要快速回复"),
        bi("Authority, fear, and urgency are pressure techniques; pause and verify independently", "权威、恐惧和紧迫性都是施压手法；应暂停并独立核实"),
        bi("Forward it to classmates first to see whether they received it", "先转发给同学，看看他们是否也收到"),
      ], answer: 2,
    },
    {
      id: "pre5", topic: "attachment",
      question: bi("Which unexpected filename creates the greatest execution risk?", "以下哪个意外收到的文件名具有最大的执行风险？"),
      options: [
        bi("tutorial-outline.pdf", "tutorial-outline.pdf"),
        bi("results.pdf.exe", "results.pdf.exe"),
        bi("reading-list.txt", "reading-list.txt"),
        bi("campus-map.png", "campus-map.png"),
      ], answer: 1,
    },
    {
      id: "pre6", topic: "login",
      question: bi("A page looks identical to the university login page but was opened from an unexpected email. What is the safest action?", "某页面外观与大学登录页面完全相同，但它来自一封意外邮件。最安全的操作是什么？"),
      options: [
        bi("Enter only the username first and see what happens", "先只输入用户名，看看会发生什么"),
        bi("Check whether the page accepts an intentionally wrong password", "输入一个故意错误的密码测试页面"),
        bi("Leave the page and navigate to the official portal through a trusted bookmark or known address", "离开页面，通过可信书签或已知地址访问官方门户"),
        bi("Continue if the logo, colours, and copyright notice look correct", "如果徽标、颜色和版权声明看起来正确就继续"),
      ], answer: 2,
    },
    {
      id: "pre7", topic: "mfa",
      question: bi("Which statement best describes multi-factor authentication (MFA)?", "以下哪项最准确地描述多因素认证（MFA）？"),
      options: [
        bi("MFA prevents every attacker who learns a password", "MFA 能阻止所有获得密码的攻击者"),
        bi("MFA reduces password-only compromise, but push approval tricks and real-time phishing can still succeed", "MFA 可降低仅凭密码入侵的风险，但推送批准诱骗和实时钓鱼仍可能成功"),
        bi("MFA makes sender and domain checks unnecessary", "使用 MFA 后无需检查发件人和域名"),
        bi("MFA protects an account only when SMS is used", "只有使用短信时，MFA 才能保护账户"),
      ], answer: 1,
    },
    {
      id: "pre8", topic: "click",
      question: bi("You clicked a suspicious link but entered nothing and downloaded nothing. What is the best next step?", "你点击了可疑链接，但没有输入信息，也没有下载任何内容。最佳下一步是什么？"),
      options: [
        bi("Close it, report the message, check for unexpected downloads, and use the official service to verify the account", "关闭页面、报告信息、检查意外下载，并通过官方服务核实账户"),
        bi("Reopen it in private browsing mode to inspect it safely", "在隐私浏览模式中重新打开，以便安全检查"),
        bi("Ignore it because no password was entered", "因为没有输入密码，所以忽略即可"),
        bi("Forward the link to a technical friend for testing", "将链接转发给懂技术的朋友测试"),
      ], answer: 0,
    },
    {
      id: "pre9", topic: "credential",
      question: bi("You entered your university password into a suspicious page. Which response is most complete?", "你在可疑页面中输入了大学账户密码。哪项响应最完整？"),
      options: [
        bi("Change the password using the link, then delete the email", "通过邮件中的链接修改密码，然后删除邮件"),
        bi("Wait for a login alert before taking action", "等收到登录提醒后再采取行动"),
        bi("Use the official portal to change the password, revoke sessions, review MFA methods, and report immediately", "通过官方门户修改密码、撤销会话、检查 MFA 方式并立即报告"),
        bi("Close the browser and run an antivirus scan only", "关闭浏览器，只运行杀毒扫描"),
      ], answer: 2,
    },
    {
      id: "pre10", topic: "verify",
      question: bi("How should you verify and report an uncertain message claiming to be from Student Services?", "应如何核实并报告一封自称来自学生服务部门的可疑邮件？"),
      options: [
        bi("Reply to the message and request proof", "回复邮件并要求对方提供证明"),
        bi("Use contact details from the official university directory and the approved reporting channel", "使用大学官方目录中的联系方式和获批准的报告渠道"),
        bi("Call the telephone number included in the message", "拨打邮件中提供的电话号码"),
        bi("Ask other students to click the link and compare results", "让其他学生点击链接并比较结果"),
      ], answer: 1,
    },
  ],

  posttest: [
    {
      id: "post1", topic: "sender",
      question: bi("“Library Notices” sends from alerts@library-notice.test and replies go to renew@quick-access.example. What is the strongest finding?", "“图书馆通知”从 alerts@library-notice.test 发出，回复地址为 renew@quick-access.example。最重要的发现是什么？"),
      options: [
        bi("Two different non-university domains conflict with the trusted display name", "两个不同的非大学域名与可信显示名称不一致"),
        bi("Libraries commonly use separate systems, so no further check is needed", "图书馆通常使用独立系统，因此无需进一步检查"),
        bi("The display name is sufficient if the email mentions a borrowed book", "如果邮件提到借阅书籍，显示名称就足够可信"),
        bi("A Reply-To address matters only after an attachment is opened", "只有打开附件后，Reply-To 地址才重要"),
      ], answer: 0,
      explanation: bi("A display name is not authenticated evidence. Compare the full From and Reply-To domains with known official domains.", "显示名称不是经过认证的证据。应将完整的发件和 Reply-To 域名与已知官方域名比较。"),
    },
    {
      id: "post2", topic: "domain",
      question: bi("Which address has files as a subdomain of southbank.example?", "以下哪个地址中的 files 是 southbank.example 的子域名？"),
      options: [
        bi("https://southbank.example.files.test", "https://southbank.example.files.test"),
        bi("https://files.southbank.example", "https://files.southbank.example"),
        bi("https://southbank-files.example", "https://southbank-files.example"),
        bi("https://files-southbank.example.test", "https://files-southbank.example.test"),
      ], answer: 1,
      explanation: bi("Read domains from right to left. In files.southbank.example, southbank.example is the controlling domain and files is its subdomain.", "域名应从右向左阅读。在 files.southbank.example 中，southbank.example 是控制域名，files 是其子域名。"),
    },
    {
      id: "post3", topic: "https",
      question: bi("A scholarship form at award-claim.test has HTTPS. What does the padlock establish?", "award-claim.test 上的奖学金表单使用 HTTPS。锁形图标能够证明什么？"),
      options: [
        bi("The scholarship provider has been approved by the university", "奖学金提供方已获大学批准"),
        bi("The form cannot store or misuse submitted data", "该表单不能存储或滥用提交的数据"),
        bi("Traffic is encrypted to award-claim.test, not that the site or scholarship is trustworthy", "与 award-claim.test 之间的流量已加密，但不能证明网站或奖学金可信"),
        bi("The browser has verified the scholarship terms", "浏览器已经核实奖学金条款"),
      ], answer: 2,
      explanation: bi("HTTPS protects data in transit to the chosen domain. Attackers can also obtain certificates for deceptive domains.", "HTTPS 保护传输到所选域名的数据。攻击者同样可以为欺骗性域名获取证书。"),
    },
    {
      id: "post4", topic: "social",
      question: bi("A message from the “Vice-Chancellor” offers a gift card for completing a confidential task today. Which cues are being combined?", "一封来自“校长”的邮件承诺，只要今天完成一项保密任务就赠送礼品卡。它组合了哪些心理线索？"),
      options: [
        bi("Authority, reward, urgency, and secrecy", "权威、奖励、紧迫性和保密要求"),
        bi("Encryption, availability, and backup", "加密、可用性和备份"),
        bi("Only curiosity, because a gift is mentioned", "只有好奇心，因为提到了礼物"),
        bi("Familiarity only, because the title is known", "只有熟悉感，因为职位名称已知"),
      ], answer: 0,
      explanation: bi("Attackers combine several pressures to suppress verification. Multiple psychological cues should make the user slow down.", "攻击者会组合多种压力来阻止核实。出现多个心理线索时，用户更应该放慢操作。"),
    },
    {
      id: "post5", topic: "attachment",
      question: bi("A tutor unexpectedly sends “Feedback_Final.pdf.scr” inside a ZIP archive. What is the safest assessment?", "导师突然在 ZIP 压缩包中发送“Feedback_Final.pdf.scr”。最安全的判断是什么？"),
      options: [
        bi("The visible .pdf text makes it a document", "文件名中可见 .pdf，说明它是文档"),
        bi("The final extension may be executable; do not extract or open it and verify independently", "最终扩展名可能表示可执行文件；不要解压或打开，应独立核实"),
        bi("ZIP compression removes executable risk", "ZIP 压缩会消除可执行风险"),
        bi("Open it if antivirus does not show a warning", "如果杀毒软件没有警告就可以打开"),
      ], answer: 1,
      explanation: bi("The final extension determines the file type. Archives and double extensions are commonly used to hide risky files.", "最终扩展名决定文件类型。压缩包和双重扩展名常被用于隐藏危险文件。"),
    },
    {
      id: "post6", topic: "login",
      question: bi("A shared-document link opens a perfect copy of the university sign-in page. Which check is most reliable?", "共享文档链接打开了大学登录页面的完美复制品。哪项检查最可靠？"),
      options: [
        bi("Whether the page uses the university colours", "页面是否使用大学配色"),
        bi("Whether password autofill appears", "是否出现密码自动填充"),
        bi("Leave it and access the document service from its known official address, checking the actual domain", "离开页面，从已知官方地址访问文档服务，并检查实际域名"),
        bi("Whether the page loads quickly and has no spelling errors", "页面是否加载迅速且没有拼写错误"),
      ], answer: 2,
      explanation: bi("Visual appearance can be copied. An independently reached official service and verified domain provide stronger evidence.", "页面外观可以被复制。通过独立方式访问的官方服务和经过核实的域名能提供更强证据。"),
    },
    {
      id: "post7", topic: "mfa",
      question: bi("You receive repeated MFA approval prompts for a login you did not start. What should you do?", "你反复收到并非由自己发起的 MFA 登录批准请求。应该怎么做？"),
      options: [
        bi("Approve one prompt to stop the notifications", "批准一次，让通知停止"),
        bi("Ignore every prompt permanently without telling anyone", "永久忽略所有请求，不通知任何人"),
        bi("Deny the prompts, use the official service to secure the account, and report the activity", "拒绝请求，通过官方服务保护账户并报告活动"),
        bi("Reply to the most recent email to ask who is logging in", "回复最新邮件，询问是谁在登录"),
      ], answer: 2,
      explanation: bi("MFA fatigue attacks rely on accidental approval. Deny, secure the account through the official service, and trigger investigation.", "MFA 疲劳攻击依赖用户误批准。应拒绝请求，通过官方服务保护账户并触发调查。"),
    },
    {
      id: "post8", topic: "click",
      question: bi("You opened a short link from a suspicious text, closed it without entering data, and saw no obvious download. What now?", "你打开了可疑短信中的短链接，没有输入数据就关闭了，也没有看到明显下载。现在该怎么办？"),
      options: [
        bi("Report it, check downloads and browser activity, and verify the account through the official service", "报告事件、检查下载和浏览器活动，并通过官方服务核实账户"),
        bi("No action is needed because the page showed no form", "页面没有显示表单，因此无需操作"),
        bi("Open the short link again to reveal its final destination", "再次打开短链接，查看最终目标"),
        bi("Post the link in a group chat to warn others", "将链接发布到群聊中警告他人"),
      ], answer: 0,
      explanation: bi("Clicking does not always mean compromise, but reporting and checking for downloads or unexpected activity are proportionate next steps.", "点击并不一定意味着已经受害，但报告并检查下载或异常活动是适当的下一步。"),
    },
    {
      id: "post9", topic: "credential",
      question: bi("You submitted a password and a one-time MFA code to a suspicious site. What is the priority?", "你向可疑网站提交了密码和一次性 MFA 验证码。首要任务是什么？"),
      options: [
        bi("Wait for the one-time code to expire", "等待一次性验证码过期"),
        bi("Through the official service, reset credentials, revoke sessions, check MFA methods, and report immediately", "通过官方服务重置凭据、撤销会话、检查 MFA 方式并立即报告"),
        bi("Change only the password if the account still opens", "如果账户仍能打开，只修改密码"),
        bi("Submit a second code to confirm whether the page is fake", "再提交一个验证码，确认页面是否虚假"),
      ], answer: 1,
      explanation: bi("A real-time attacker may already hold an authenticated session. Password change, session revocation, MFA review, and rapid reporting are all needed.", "实时攻击者可能已经获得认证会话。需要同时修改密码、撤销会话、检查 MFA 并迅速报告。"),
    },
    {
      id: "post10", topic: "verify",
      question: bi("An unexpected tuition refund email may be genuine. How should you decide?", "一封意外的学费退款邮件可能是真实的。应该如何判断？"),
      options: [
        bi("Use the message's telephone number but do not click its link", "使用邮件中的电话号码，但不点击链接"),
        bi("Reply and ask the sender to confirm your student number", "回复邮件，请发件人确认你的学号"),
        bi("Open the known official finance portal or use the university directory, then report the suspicious message if unconfirmed", "打开已知官方财务门户或使用大学官方目录；如果无法确认，则报告可疑信息"),
        bi("Search the displayed sender name and use the first result", "搜索显示的发件人名称并使用第一个结果"),
      ], answer: 2,
      explanation: bi("Independent verification avoids every contact path supplied by a potentially malicious message and preserves a route for reporting.", "独立核实能够避开潜在恶意信息提供的所有联系路径，并保留正式报告渠道。"),
    },
  ],

  lessons: [
    {
      id: "attack", number: "01", title: bi("The complete phishing attack flow", "网络钓鱼攻击的完整流程"),
      summary: bi("Follow the attacker from research to account abuse.", "从信息收集一直追踪到攻击者滥用账户。"),
      purpose: bi("Obtain access, money, data, or a trusted account for further attacks.", "获取访问权限、资金、数据，或用于后续攻击的可信账户。"),
      techniques: bi("Research public information → craft a believable lure → impersonate trust → redirect or attach → capture access → abuse the account.", "收集公开信息 → 制作可信诱饵 → 冒充可信身份 → 引导跳转或附加文件 → 获取权限 → 滥用账户。"),
      signals: bi("Unexpected relevance, unusual timing, mismatched identity, pressure, and requests that move outside normal university workflows.", "异常相关性、异常时间、身份不一致、施压，以及要求离开正常大学流程的操作。"),
      why: bi("Personal details and familiar workflows reduce suspicion; each successful step makes the next request appear more credible.", "个人信息和熟悉流程会降低怀疑；每个成功步骤都会让下一项请求显得更可信。"),
      user: bi("Pause at any trust transition, inspect identity and destination, then verify independently.", "在每次信任转换处暂停，检查身份和目标地址，然后独立核实。"),
      organisation: bi("Limit exposed information, filter email, protect domains, monitor authentication, and prepare rapid response.", "限制公开信息、过滤邮件、保护域名、监控认证并准备快速响应。"),
      limitation: bi("Filtering the first message does not remove later abuse if a real account or session has already been captured.", "过滤第一封邮件并不能消除后续滥用，特别是在真实账户或会话已经被窃取时。"),
      tradeoff: bi("Reducing public information can limit attacker research, but universities still need open directories, collaboration, and accessible services.", "减少公开信息可以限制攻击者收集资料，但大学仍需要公开目录、协作和易于访问的服务。"),
      example: bi("A fictional attacker reads a public club page, sends a tailored “committee file” from club-share.test, and tries to capture a student login. The example contains no live link.", "一名虚构攻击者查看公开社团页面，从 club-share.test 发送定制的“委员会文件”，并试图窃取学生登录信息。示例不包含真实链接。"),
      flow: [bi("Research", "收集信息"), bi("Build lure", "制作诱饵"), bi("Impersonate", "冒充身份"), bi("Redirect", "引导跳转"), bi("Capture", "获取权限"), bi("Abuse", "滥用账户")],
    },
    {
      id: "sender", number: "02", title: bi("Sender impersonation", "发件人伪装"),
      summary: bi("Separate the friendly label from the addressing evidence.", "将友好的显示标签与真实地址证据区分开。"),
      purpose: bi("Make an external attacker appear to be a lecturer, service desk, library, or student organisation.", "让外部攻击者看起来像讲师、服务台、图书馆或学生组织。"),
      techniques: bi("Copied display names, lookalike From domains, different Reply-To addresses, and compromised legitimate accounts.", "复制显示名称、仿冒发件域名、不同的 Reply-To 地址，以及被入侵的合法账户。"),
      signals: bi("Full address differs from the display name; Reply-To changes domain; spelling has added, removed, or substituted characters.", "完整地址与显示名称不一致；Reply-To 更换域名；拼写中增加、删除或替换字符。"),
      why: bi("Mail interfaces emphasise names and avatars, while full technical addresses are often hidden.", "邮件界面突出姓名和头像，而完整技术地址通常被隐藏。"),
      user: bi("Expand sender details, compare From and Reply-To, and verify unexpected requests using known contact details.", "展开发件人详情，比较 From 和 Reply-To，并使用已知联系方式核实异常请求。"),
      organisation: bi("Use authenticated mail controls, domain monitoring, clear official domains, and warnings for external senders.", "使用邮件认证控制、域名监控、清晰的官方域名和外部发件人警告。"),
      limitation: bi("A correct official domain can still be dangerous when the real mailbox is compromised; authentication proves a sending path, not the sender's current intent.", "真实邮箱被入侵时，正确的官方域名仍可能带来危险；邮件认证证明发送路径，并不能证明当前请求的真实意图。"),
      tradeoff: bi("External-sender warnings help with lookalike domains, but frequent banners can become background noise and do not cover compromised internal accounts.", "外部发件人警告有助于发现仿冒域名，但频繁横幅可能被忽略，也无法覆盖被入侵的内部账户。"),
      example: bi("“Southbank Library” displays above renew@library-help.test, while replies go to access@book-renewal.example. Both are fictional.", "“Southbank 图书馆”显示在 renew@library-help.test 上方，而回复会发送到 access@book-renewal.example。两者均为虚构。"),
    },
    {
      id: "links", number: "03", title: bi("Domains and link analysis", "域名与链接分析"),
      summary: bi("Find the controlling domain before trusting the page.", "在信任页面之前先找出控制域名。"),
      purpose: bi("Move the user to infrastructure controlled by the attacker while preserving familiar words and branding.", "在保留熟悉文字和品牌的同时，将用户引导到攻击者控制的基础设施。"),
      techniques: bi("Misleading subdomains, similar spelling, extra characters, different display text, short links, and HTTPS on deceptive domains.", "误导性子域名、相似拼写、多余字符、显示文字与实际目标不同、短链接，以及欺骗性域名上的 HTTPS。"),
      signals: bi("The important domain is not the expected one; a familiar name appears only on the left; destination and displayed text differ.", "关键域名不是预期域名；熟悉名称只出现在左侧；实际目标与显示文字不同。"),
      why: bi("People read left to right and recognise brands faster than they parse domain boundaries.", "人们从左向右阅读，识别品牌的速度比分析域名边界更快。"),
      user: bi("Read the hostname right to left, avoid opening shortened links, and navigate independently to known services.", "从右向左读取主机名，避免打开短链接，并独立访问已知服务。"),
      organisation: bi("Filter known malicious URLs, rewrite and inspect links safely, monitor lookalike domains, and publish canonical addresses.", "过滤已知恶意 URL，安全重写和检查链接，监控仿冒域名，并公布标准官方地址。"),
      limitation: bi("A familiar or official domain is strong evidence, but compromised pages, redirects, and third-party services still require context checks.", "熟悉或官方域名属于较强证据，但被入侵页面、重定向和第三方服务仍需要结合上下文检查。"),
      tradeoff: bi("Link rewriting and blocking improve detection, but they can hide the original destination, create false positives, or delay legitimate access.", "链接重写和阻止能够加强发现能力，但也可能隐藏原始目标、产生误报或延迟正常访问。"),
      example: bi("portal.southbank.example is within southbank.example; southbank.example.login-check.test is controlled under login-check.test.", "portal.southbank.example 位于 southbank.example 之下；southbank.example.login-check.test 则受 login-check.test 控制。"),
    },
    {
      id: "psychology", number: "04", title: bi("Social engineering psychology", "社会工程心理"),
      summary: bi("Recognise pressure designed to replace careful verification.", "识别旨在取代谨慎核实的心理压力。"),
      purpose: bi("Trigger fast action before the user checks identity, context, or consequences.", "促使用户在检查身份、上下文和后果之前快速行动。"),
      techniques: bi("Urgency, fear, authority, reward, curiosity, familiarity, secrecy, and helpfulness.", "紧迫感、恐惧、权威、奖励、好奇心、熟悉感、保密要求和助人心理。"),
      signals: bi("Very short deadlines, threats, unusual secrecy, unexpected prizes, emotionally charged language, or requests from senior roles.", "极短期限、威胁、异常保密要求、意外奖励、情绪化语言或来自高级职位的请求。"),
      why: bi("Stress narrows attention; authority and familiarity reduce the perceived need to challenge a request.", "压力会缩小注意范围；权威和熟悉感会降低质疑请求的意愿。"),
      user: bi("Name the pressure, slow down, and verify through a channel the message did not supply.", "识别施压方式，放慢操作，并通过信息未提供的渠道核实。"),
      organisation: bi("Design workflows without artificial urgency, empower challenge, and train staff without victim blaming.", "设计不制造虚假紧迫性的流程，鼓励质疑，并以不责怪受害者的方式培训人员。"),
      limitation: bi("Urgency, authority, and confidentiality also occur in legitimate university work, so psychology is a prompt to verify rather than proof of phishing.", "紧迫、权威和保密也会出现在正常大学工作中，因此心理信号用于提醒核实，并不能单独证明网络钓鱼。"),
      tradeoff: bi("Removing every urgent workflow is unrealistic; the safer design is a rapid verification path that does not punish careful delay.", "消除所有紧急流程并不现实，更安全的设计是提供快速核实渠道，并允许用户为谨慎检查而短暂停顿。"),
      example: bi("A fictional “Dean” at executive-task.test offers a reward for a secret purchase within 15 minutes.", "一名来自 executive-task.test 的虚构“院长”承诺，只要在 15 分钟内秘密采购就给予奖励。"),
    },
    {
      id: "attachments", number: "05", title: bi("Suspicious attachments", "可疑附件"),
      summary: bi("Treat unexpected file types and hidden execution paths as risk.", "将意外文件类型和隐藏执行路径视为风险。"),
      purpose: bi("Execute malicious code, open a credential-capture page, or hide harmful content from filters and users.", "执行恶意代码、打开凭据窃取页面，或向过滤器和用户隐藏有害内容。"),
      techniques: bi("HTML attachments, ZIP archives, macro documents, executables, and double extensions such as Notes.pdf.exe.", "HTML 附件、ZIP 压缩包、宏文档、可执行文件，以及 Notes.pdf.exe 等双重扩展名。"),
      signals: bi("Unexpected delivery, unusual extension, archive password, macro prompt, executable final extension, or pressure to bypass warnings.", "意外送达、异常扩展名、压缩包密码、宏提示、可执行的最终扩展名，或要求绕过警告。"),
      why: bi("File icons and the first extension can look familiar; archives and HTML files may evade ordinary expectations.", "文件图标和第一个扩展名可能看起来很熟悉；压缩包和 HTML 文件可能绕过常规预期。"),
      user: bi("Do not open or forward it. Verify through a known channel and use the official reporting process.", "不要打开或转发。通过已知渠道核实，并使用正式报告流程。"),
      organisation: bi("Block risky types, sandbox attachments, disable untrusted macros, apply endpoint controls, and preserve incident evidence.", "阻止危险类型、在沙箱中检查附件、禁用不可信宏、应用终端控制并保留事件证据。"),
      limitation: bi("Sandboxes and endpoint tools can miss password-protected, delayed, or user-approved behaviour; file extension is evidence, not a complete verdict.", "沙箱和终端工具可能漏掉受密码保护、延迟运行或由用户批准的行为；文件扩展名属于判断证据，并非完整结论。"),
      tradeoff: bi("Blocking archives, macros, or HTML reduces attack paths but can interfere with legitimate teaching and research files.", "阻止压缩包、宏或 HTML 可以减少攻击路径，但也可能影响正常教学和研究文件。"),
      example: bi("A fictional tutor message includes Feedback.pdf.scr inside review-files.test.zip. Nothing in this activity executes or downloads.", "一封虚构导师邮件在 review-files.test.zip 中包含 Feedback.pdf.scr。本活动不会执行或下载任何内容。"),
    },
    {
      id: "login", number: "06", title: bi("Fake login pages, sessions, and MFA", "虚假登录页面、会话与 MFA"),
      summary: bi("A familiar page can still capture credentials and live sessions.", "熟悉的页面仍可能窃取凭据和实时会话。"),
      purpose: bi("Steal passwords, one-time codes, MFA approvals, recovery details, or authenticated session tokens.", "窃取密码、一次性验证码、MFA 批准、恢复信息或已认证会话令牌。"),
      techniques: bi("Copied login design, reverse-proxy phishing, MFA fatigue prompts, fake QR sign-in, and requests to re-authenticate.", "复制登录设计、反向代理钓鱼、MFA 疲劳推送、虚假二维码登录和重新认证请求。"),
      signals: bi("Unexpected login prompt, wrong domain, repeated MFA prompts, unusual QR code, or sign-in requested after following an unsolicited link.", "意外登录提示、错误域名、重复 MFA 请求、异常二维码，或通过未经请求的链接访问后要求登录。"),
      why: bi("Branding is easy to copy; real-time attackers can relay credentials and MFA challenges while the user is present.", "品牌外观很容易复制；实时攻击者可以在用户操作时转发凭据和 MFA 挑战。"),
      user: bi("Leave the page, use the official service, deny unfamiliar MFA prompts, and report repeated authentication requests.", "离开页面，使用官方服务，拒绝陌生 MFA 请求，并报告重复认证请求。"),
      organisation: bi("Deploy phishing-resistant MFA where possible, protect sessions, detect impossible travel, and make session revocation rapid.", "尽可能部署抗钓鱼 MFA，保护会话，检测不可能旅行，并支持快速撤销会话。"),
      limitation: bi("MFA reduces password-only compromise, but approved prompts, stolen sessions, weak recovery, and compromised devices can bypass its protection.", "MFA 可以降低仅凭密码入侵的风险，但已批准推送、被窃取会话、薄弱恢复流程和被入侵设备仍可能绕过保护。"),
      tradeoff: bi("Phishing-resistant authentication provides stronger assurance but requires compatible devices, enrolment support, and safe recovery procedures.", "抗钓鱼认证提供更强保证，但需要兼容设备、注册支持和安全恢复流程。"),
      example: bi("login.southbank.example is the fictional known portal; southbank-login.account-check.test is a safe example of a lookalike target.", "login.southbank.example 是虚构的已知门户；southbank-login.account-check.test 是安全的仿冒目标示例。"),
    },
    {
      id: "controls", number: "07", title: bi("Layered defence", "分层防御"),
      summary: bi("Use controls across prevention, detection, response, and recovery.", "在预防、发现、响应和恢复阶段使用控制措施。"),
      purpose: bi("Reduce the chance of success and limit harm when one control fails.", "降低攻击成功概率，并在某项控制失效时限制损害。"),
      techniques: bi("Attackers adapt around single controls by changing domains, messages, files, identities, and timing.", "攻击者通过改变域名、信息、文件、身份和时机来绕过单一控制。"),
      signals: bi("Repeated campaigns, bypassed filters, unusual logins, many recipients, reports from users, or newly registered lookalike domains.", "重复攻击、绕过过滤器、异常登录、大量收件人、用户报告或新注册的仿冒域名。"),
      why: bi("No user is perfectly attentive and no technical filter has complete information. Defence must tolerate human and technical failure.", "没有用户能够永远保持警觉，也没有技术过滤器掌握全部信息。防御必须能够容忍人员和技术失误。"),
      user: bi("Recognise, pause, verify, report, and follow recovery guidance without hiding mistakes.", "识别、暂停、核实、报告，并按照恢复指导操作，不隐瞒失误。"),
      organisation: bi("Combine filtering, domain protection, MFA, least privilege, training, monitoring, incident response, and recovery.", "组合邮件过滤、域名保护、MFA、最小权限、培训、监控、事件响应和恢复。"),
      limitation: bi("Every layer can fail: users can be persuaded, filters miss new variants, authentication can be approved, and response can be delayed.", "每一层都可能失效：用户可能受到诱导，过滤器会漏掉新变体，认证请求可能被批准，响应也可能延迟。"),
      tradeoff: bi("More blocking and monitoring can increase false positives, privacy concerns, support workload, and user workarounds.", "更多阻止和监控可能增加误报、隐私顾虑、支持工作量和用户绕过行为。"),
      example: bi("A fictional campaign at invoice-alert.test is filtered for most users; one report lets the organisation quarantine the remaining messages and revoke an exposed session.", "来自 invoice-alert.test 的虚构攻击大多被过滤；一名用户的报告使组织能够隔离剩余邮件并撤销已暴露会话。"),
    },
    {
      id: "incident", number: "08", title: bi("Incident response by exposure level", "按暴露程度进行事件响应"),
      summary: bi("Choose actions that match what actually happened.", "根据实际发生的情况选择响应措施。"),
      purpose: bi("Attackers benefit from delay, unreported exposure, active sessions, and users continuing to interact.", "攻击者会利用延迟报告、未披露的暴露、活动会话和用户继续操作。"),
      techniques: bi("Messages seek a sequence: open, click, enter, approve, execute, then remain silent.", "攻击信息试图推动一系列动作：打开、点击、输入、批准、执行，然后让用户保持沉默。"),
      signals: bi("No click; click without input; credentials entered; MFA approved; attachment opened; or signs of account and device misuse.", "未点击；点击但未输入；已输入凭据；已批准 MFA；已打开附件；或出现账户和设备被滥用的迹象。"),
      why: bi("Shame and uncertainty delay reporting, while attackers can use credentials and sessions within minutes.", "羞耻感和不确定性会延迟报告，而攻击者可能在几分钟内利用凭据和会话。"),
      user: bi("Stop interaction, record what occurred, use official support, secure accounts, and isolate a device when instructed.", "停止操作，记录发生的情况，使用官方支持渠道，保护账户，并在得到指示时隔离设备。"),
      organisation: bi("Triage exposure, quarantine messages, block indicators, revoke access, examine devices, communicate, recover, and improve controls.", "对暴露程度分级，隔离邮件，阻止指标，撤销访问，检查设备，沟通、恢复并改进控制。"),
      limitation: bi("The visible user action may not reveal the full exposure; responders need logs, device evidence, and an accurate timeline.", "用户看到的操作可能无法说明全部暴露，响应人员仍需要日志、设备证据和准确时间线。"),
      tradeoff: bi("Rapid isolation limits harm but can interrupt study and destroy volatile evidence if users improvise outside the response process.", "快速隔离可以限制损害，但用户自行处理可能中断学习，也可能破坏短暂存在的证据。"),
      example: bi("A student opens fileshare-notice.example but enters nothing: they close it, report it, check downloads, and use the known portal. If a file ran, they contact IT and stop using the device.", "学生打开 fileshare-notice.example 但未输入内容：关闭页面、报告、检查下载并使用已知门户。如果文件已运行，则联系 IT 并停止使用设备。"),
    },
  ],

  emailScenarios: [
    {
      id: "account", label: bi("1 · Account expiry", "1 · 账户失效"), avatar: "IT",
      toolbar: bi("Southbank Mail · Simulation", "Southbank 邮箱 · 模拟"),
      calibration: bi("Urgency by itself is not proof of phishing. The risk becomes high because urgency is combined with an external lookalike domain, a different Reply-To, a credential request, and a fake destination.", "紧迫性本身不能证明网络钓鱼。本场景的高风险来自多个证据组合，包括外部仿冒域名、不同的 Reply-To、凭据请求和虚假目标地址。"),
      measurement: bi("The first-attempt score measures how many marked signals were found before the answer list was shown. It does not measure every part of domain reasoning.", "首次得分记录答案列表显示前找到的标记信号数量，它不能测量域名推理的全部内容。"),
      elements: [
        { id: "urgent", area: "subject", display: bi("URGENT: Student account expires in 20 minutes", "紧急：学生账户将在 20 分钟后失效"), label: bi("Artificial urgency", "人为制造的紧迫性"), objective: bi("Force action before verification.", "迫使用户在核实前采取行动。"), deception: bi("A precise short deadline creates fear of losing study access.", "明确而短暂的期限会制造失去学习权限的恐惧。"), check: bi("Open the known portal independently and check account notices.", "独立打开已知门户并检查账户通知。"), control: bi("Clear official communication rules and rapid reporting.", "清晰的官方沟通规则和快速报告。") },
        { id: "display", area: "senderName", display: bi("Southbank University IT Support", "Southbank 大学 IT 支持"), label: bi("Trusted display name", "可信显示名称"), objective: bi("Borrow the university's authority.", "借用大学的权威。"), deception: bi("Mail clients emphasise a name that the sender can type freely.", "邮件客户端突出显示可由发件人自由填写的名称。"), check: bi("Treat the display name as a label, then inspect the full address.", "将显示名称视为标签，然后检查完整地址。"), control: bi("External-sender banners and authenticated mail controls.", "外部发件人横幅和邮件认证控制。") },
        { id: "from", area: "senderEmail", display: bi("accounts@southbank-support.example", "accounts@southbank-support.example"), label: bi("Lookalike sender domain", "仿冒发件域名"), objective: bi("Appear related to the university without using its known domain.", "在不使用已知大学域名的情况下显得与大学有关。"), deception: bi("The university name appears before a plausible extra word.", "大学名称出现在一个看似合理的附加词之前。"), check: bi("Compare the complete domain with a known official address.", "将完整域名与已知官方地址比较。"), control: bi("Domain monitoring, mail filtering, and published canonical domains.", "域名监控、邮件过滤和公布标准官方域名。") },
        { id: "reply", area: "replyTo", display: bi("case-991@account-review.test", "case-991@account-review.test"), label: bi("Different Reply-To", "不同的 Reply-To"), objective: bi("Move replies to attacker-controlled infrastructure.", "将回复引导到攻击者控制的基础设施。"), deception: bi("Reply-To is usually hidden until sender details are expanded.", "Reply-To 通常在展开发件人详情前被隐藏。"), check: bi("Compare From and Reply-To before responding.", "回复前比较 From 和 Reply-To。"), control: bi("Flag unusual reply routing and external domains.", "标记异常回复路由和外部域名。") },
        { id: "request", area: "body", display: bi("Confirm your username, password, and current MFA code to keep access.", "确认用户名、密码和当前 MFA 验证码以保留访问权限。"), label: bi("Credential request", "凭据请求"), objective: bi("Capture credentials and a live second factor.", "窃取凭据和实时第二认证因素。"), deception: bi("Account continuity makes the request feel necessary.", "维持账户使用的理由让请求显得必要。"), check: bi("Official support should not request a password or MFA code by email.", "官方支持不应通过邮件索要密码或 MFA 验证码。"), control: bi("Phishing-resistant MFA and clear credential-handling policy.", "抗钓鱼 MFA 和清晰的凭据处理政策。") },
        { id: "linkText", area: "link", display: bi("Open the Southbank secure portal", "打开 Southbank 安全门户"), label: bi("Misleading link text", "误导性链接文字"), objective: bi("Make a foreign destination look official.", "让外部目标看起来像官方网站。"), deception: bi("The clickable words are not the destination.", "可点击文字并不等于实际目标。"), check: bi("Inspect the destination without opening it; navigate independently instead.", "在不打开的情况下检查目标；应改为独立访问。"), control: bi("Safe-link analysis and user-visible destination previews.", "安全链接分析和用户可见的目标预览。") },
        { id: "domain", area: "destination", display: bi("Simulated target: southbank-login.account-check.test", "模拟目标：southbank-login.account-check.test"), label: bi("Attacker-controlled domain", "攻击者控制的域名"), objective: bi("Host a fake university sign-in page.", "托管虚假大学登录页面。"), deception: bi("The word southbank is placed on the left, but account-check.test controls the address.", "southbank 位于左侧，但真正控制地址的是 account-check.test。"), check: bi("Read the hostname from right to left and find the controlling domain.", "从右向左读取主机名，找出控制域名。"), control: bi("URL filtering and lookalike-domain monitoring.", "URL 过滤和仿冒域名监控。") },
      ],
    },
    {
      id: "reward", label: bi("2 · Scholarship refund", "2 · 奖学金退款"), avatar: "$",
      toolbar: bi("Student Finance · Simulation", "学生财务 · 模拟"),
      calibration: bi("A reward, refund, or request for bank details can occur in legitimate processes. The decision should depend on application history, minimum necessary data, the real domain, and an independently reached finance service.", "奖励、退款或银行资料请求也可能出现在正常流程中。判断应结合申请记录、最低必要资料、真实域名和独立访问的财务服务。"),
      measurement: bi("The scenario measures recognition of a combined fraud pattern. It does not prove that the learner can evaluate every genuine financial process.", "本场景测量对组合欺诈模式的识别，它不能证明学习者能够判断所有真实财务流程。"),
      elements: [
        { id: "reward", area: "subject", display: bi("You have been selected for a $2,400 scholarship refund", "你已获得 2,400 美元奖学金退款"), label: bi("Unexpected reward", "意外奖励"), objective: bi("Create excitement that suppresses verification.", "制造兴奋感以抑制核实。"), deception: bi("A specific amount and student theme make an unsolicited prize feel personal.", "具体金额和学生主题使未经请求的奖励显得个性化。"), check: bi("Check the known finance portal for an existing application or notice.", "在已知财务门户中检查是否存在申请或通知。"), control: bi("Publish award processes and warn about unsolicited claims.", "公布奖励流程并警示未经请求的申领。") },
        { id: "display", area: "senderName", display: bi("Southbank Scholarships Office", "Southbank 奖学金办公室"), label: bi("Authority and familiarity", "权威与熟悉感"), objective: bi("Borrow a trusted university function.", "借用可信大学职能。"), deception: bi("The title sounds routine even though the recipient never applied.", "即使收件人从未申请，该名称仍听起来像正常业务。"), check: bi("Compare the claim with your real application history.", "将通知与自己的真实申请记录比较。"), control: bi("Consistent official channels for financial notices.", "对财务通知采用一致的官方渠道。") },
        { id: "from", area: "senderEmail", display: bi("refunds@southbank-awards.example", "refunds@southbank-awards.example"), label: bi("Unofficial finance domain", "非官方财务域名"), objective: bi("Appear connected to the university while staying attacker-controlled.", "在保持攻击者控制的同时显得与大学有关。"), deception: bi("The domain combines trusted words in a plausible order.", "域名以合理顺序组合可信词语。"), check: bi("Use the university directory to identify the official finance domain.", "使用大学官方目录识别财务部门域名。"), control: bi("Domain protection and external sender labelling.", "域名保护和外部发件人标记。") },
        { id: "reply", area: "replyTo", display: bi("claim-urgent@fast-refund.test", "claim-urgent@fast-refund.test"), label: bi("Urgent reply channel", "紧急回复渠道"), objective: bi("Move conversation away from monitored university systems.", "将对话移出受监控的大学系统。"), deception: bi("The address appears to describe a specialised refund processor.", "地址看起来像专业退款处理方。"), check: bi("Do not use contact details supplied by the claim message.", "不要使用申领信息中提供的联系方式。"), control: bi("Monitor reply-domain mismatches and financial impersonation.", "监控回复域名不匹配和财务身份冒充。") },
        { id: "request", area: "body", display: bi("Submit your student number, date of birth, bank account, and a photo of your ID today.", "请于今天提交学号、出生日期、银行账户和身份证件照片。"), label: bi("Excessive information request", "过度的信息请求"), objective: bi("Collect identity and financial data for fraud.", "收集身份和财务数据用于欺诈。"), deception: bi("Refunds plausibly involve payment details, making extra requests easier to accept.", "退款看似需要支付信息，使额外请求更容易被接受。"), check: bi("Ask what data an official process requires, using the known finance office.", "通过已知财务部门确认官方流程需要哪些数据。"), control: bi("Data minimisation, authenticated portals, and privacy review.", "数据最小化、认证门户和隐私审查。") },
        { id: "link", area: "link", display: bi("Complete the secure refund form", "填写安全退款表单"), label: bi("Trust-building link text", "建立信任的链接文字"), objective: bi("Move the user to a data-capture form.", "将用户引导到数据收集表单。"), deception: bi("The word secure describes a claim, not a verified property.", "“安全”一词只是描述，并非经过验证的属性。"), check: bi("Ignore the label and inspect the actual destination.", "忽略标签，检查实际目标。"), control: bi("Link inspection, filtering, and known official forms.", "链接检查、过滤和已知官方表单。") },
        { id: "domain", area: "destination", display: bi("Simulated target: grant-form.student-prize.test", "模拟目标：grant-form.student-prize.test"), label: bi("Prize-themed target domain", "奖励主题目标域名"), objective: bi("Host the fraudulent personal-data form.", "托管欺诈性个人数据表单。"), deception: bi("The domain sounds relevant but has no demonstrated university relationship.", "域名听起来相关，但没有证据表明与大学有关。"), check: bi("Find the controlling domain and compare it with a known official service.", "找出控制域名，并与已知官方服务比较。"), control: bi("Block known campaign infrastructure and publish official form locations.", "阻止已知攻击基础设施并公布官方表单位置。") },
      ],
    },
    {
      id: "attachment", label: bi("3 · Shared research file", "3 · 共享研究文件"), avatar: "PC",
      toolbar: bi("Course Mail · Simulation", "课程邮件 · 模拟"),
      calibration: bi("Lecturers legitimately share archives and time-sensitive feedback. Risk rises when the request also bypasses the normal course platform, uses unrelated addressing, and delivers executable web content.", "讲师确实可能共享压缩包和有时限的反馈。风险上升是因为请求同时绕过正常课程平台、使用无关地址，并投递可执行网页内容。"),
      measurement: bi("The marked elements support guided practice. Formal evaluation should also ask the participant to explain which combination changed the decision.", "标记元素用于引导练习。正式评价还应要求参与者说明哪些证据组合改变了判断。"),
      elements: [
        { id: "context", area: "subject", display: bi("Professor Chen shared your confidential research feedback", "Chen 教授共享了你的机密研究反馈"), label: bi("Unexpected confidential context", "意外的机密情境"), objective: bi("Create curiosity and discourage consultation.", "制造好奇心并阻止用户咨询他人。"), deception: bi("A familiar lecturer and private feedback feel personally relevant.", "熟悉的讲师和私人反馈让信息显得与个人高度相关。"), check: bi("Check the real course platform for a matching assessment or message.", "在真实课程平台中检查是否有对应评估或信息。"), control: bi("Use consistent learning-platform workflows for feedback.", "对反馈采用一致的学习平台流程。") },
        { id: "display", area: "senderName", display: bi("Professor Mei Chen", "Mei Chen 教授"), label: bi("Familiar person impersonation", "冒充熟悉人员"), objective: bi("Use a known authority to make the file feel expected.", "利用已知权威让文件显得符合预期。"), deception: bi("The display name matches someone the student may know.", "显示名称与学生可能认识的人一致。"), check: bi("Compare the full address and contact the lecturer through the course platform.", "比较完整地址，并通过课程平台联系讲师。"), control: bi("Protect staff accounts and label external senders.", "保护教职员工账户并标记外部发件人。") },
        { id: "from", area: "senderEmail", display: bi("shared-doc@faculty-files.example", "shared-doc@faculty-files.example"), label: bi("Generic external sender", "通用外部发件地址"), objective: bi("Deliver an attachment while borrowing a lecturer's name.", "借用讲师姓名投递附件。"), deception: bi("The domain sounds academic without matching a known institution.", "域名听起来像学术服务，但不匹配已知机构。"), check: bi("Verify the lecturer's address through the directory or course site.", "通过官方目录或课程网站核实讲师地址。"), control: bi("Sender authentication and compromised-account monitoring.", "发件人认证和账户入侵监控。") },
        { id: "reply", area: "replyTo", display: bi("review@document-access.test", "review@document-access.test"), label: bi("External Reply-To", "外部 Reply-To"), objective: bi("Capture responses outside university monitoring.", "在大学监控之外获取回复。"), deception: bi("A document-service name sounds normal for shared files.", "文档服务名称对于共享文件听起来很正常。"), check: bi("Expand details and compare From, Reply-To, and expected service.", "展开详情，比较 From、Reply-To 和预期服务。"), control: bi("Detect reply redirection and suspicious external services.", "检测回复重定向和可疑外部服务。") },
        { id: "pressure", area: "body", display: bi("Open the file before tonight's supervisor meeting; do not upload it to the course site.", "请在今晚导师会议前打开文件；不要上传到课程网站。"), label: bi("Urgency plus workflow bypass", "紧迫性加绕过流程"), objective: bi("Prevent verification and move activity outside controlled systems.", "阻止核实并将活动移出受控系统。"), deception: bi("A real meeting makes the deadline and secrecy sound plausible.", "真实会议让期限和保密要求显得合理。"), check: bi("Ask whether the request fits the normal feedback workflow.", "检查请求是否符合正常反馈流程。"), control: bi("Safe standard workflows and a culture that permits challenge.", "安全标准流程和允许质疑的文化。") },
        { id: "attachment", area: "attachment", display: bi("Research_Feedback.pdf.html · simulated · 24 KB", "Research_Feedback.pdf.html · 模拟 · 24 KB"), label: bi("HTML double extension", "HTML 双重扩展名"), objective: bi("Open a local fake login page disguised as a PDF.", "打开伪装成 PDF 的本地虚假登录页面。"), deception: bi("The first extension and filename suggest a harmless document; the final .html controls the type.", "第一个扩展名和文件名暗示无害文档，但最终的 .html 决定文件类型。"), check: bi("Read the final extension and verify the attachment before opening.", "读取最终扩展名，并在打开前核实附件。"), control: bi("Block risky attachment types and sandbox files.", "阻止危险附件类型并在沙箱中检查文件。") },
        { id: "archive", area: "attachment", display: bi("Supporting_Data.zip · simulated · 86 KB", "Supporting_Data.zip · 模拟 · 86 KB"), label: bi("Unexpected archive", "意外压缩包"), objective: bi("Hide files from casual inspection and some filters.", "向普通检查和部分过滤器隐藏文件。"), deception: bi("Research data is often compressed, so the format fits the story.", "研究数据经常被压缩，因此该格式符合故事情境。"), check: bi("Do not extract it; confirm the sharing event through the known platform.", "不要解压；通过已知平台确认共享事件。"), control: bi("Archive scanning, endpoint protection, and approved file-sharing services.", "压缩包扫描、终端保护和获批准的文件共享服务。") },
      ],
    },
  ],

  defenceScenarios: [
    {
      id: "unopened", title: bi("Suspicious email, nothing clicked", "收到可疑邮件，尚未点击"), context: bi("The message requests an urgent portal login, but you have not interacted with it.", "邮件要求紧急登录门户，但你尚未与其交互。"),
      options: [bi("Delete it immediately and tell nobody", "立即删除，不通知任何人"), bi("Pause, inspect it without opening content, verify independently, and report through the official channel", "暂停，在不打开内容的情况下检查，独立核实并通过官方渠道报告"), bi("Reply and ask the sender to prove their identity", "回复并要求发件人证明身份")], answer: 1,
      risks: [bi("Deleting alone removes evidence and does not help protect other recipients.", "仅删除会丢失证据，也无法帮助保护其他收件人。"), bi("This preserves safety and gives the organisation early warning.", "这既能保证安全，也能向组织提供早期预警。"), bi("Replying confirms an active account and keeps you inside the attacker's channel.", "回复会确认账户处于活动状态，并让你继续留在攻击者控制的渠道中。")],
      correctWhy: bi("No exposure has occurred, so the priority is safe verification, reporting, and preventing wider impact.", "尚未发生暴露，因此重点是安全核实、报告并防止更广泛影响。"), userNext: bi("Use the reporting function, then follow local guidance on retaining or deleting the message.", "使用报告功能，然后按照本地指导保留或删除邮件。"), orgNext: bi("Triage the report, search for matching messages, and block confirmed indicators.", "对报告进行分级，搜索相同邮件并阻止已确认的指标。"),
      layer: bi("Prevention and detection: stop interaction while creating an early signal for organisation-wide search and blocking.", "预防与发现：停止交互，同时为组织范围搜索和阻止提供早期信号。"),
      residual: bi("The message may still have reached other users. Deleting one copy protects only one mailbox and can remove useful evidence.", "邮件可能已经到达其他用户。删除一个副本只能保护一个邮箱，还可能移除有用证据。"),
    },
    {
      id: "clicked", title: bi("Link clicked, no information entered", "已点击链接，但未输入信息"), context: bi("A page opened, but you entered nothing and noticed no download.", "页面已经打开，但你没有输入任何信息，也没有发现下载。"),
      options: [bi("Close it, record what happened, report it, check downloads, and verify the account through the official service", "关闭页面，记录经过，报告事件，检查下载，并通过官方服务核实账户"), bi("Reopen it in private mode to identify the site", "在隐私模式中重新打开以识别网站"), bi("Take no action because no password was entered", "因为没有输入密码，所以不采取行动")], answer: 0,
      risks: [bi("This proportionate response limits further interaction and supports investigation.", "这种适当响应能限制进一步交互并支持调查。"), bi("Private mode does not make a malicious site safe and creates another exposure.", "隐私模式不会使恶意网站变安全，还会造成再次暴露。"), bi("A click may still trigger downloads, browser exploitation, or useful campaign telemetry.", "点击仍可能触发下载、浏览器漏洞利用或为攻击者提供活动信息。")],
      correctWhy: bi("A click is not proof of compromise, but it justifies stopping, checking, and reporting without revisiting the site.", "点击并不能证明已经受害，但足以要求停止操作、检查和报告，且不要再次访问。"), userNext: bi("Check browser downloads and official account activity; follow IT guidance if anything unexpected appears.", "检查浏览器下载和官方账户活动；如发现异常，遵循 IT 指导。"), orgNext: bi("Analyse the inert indicator safely, search logs, and warn or protect other recipients.", "安全分析非活动指标，搜索日志，并警告或保护其他收件人。"),
      layer: bi("Detection and response: establish what loaded, check for downloads or account activity, and contain the campaign without assuming compromise.", "发现与响应：确认页面加载内容，检查下载或账户活动，并在不直接假设已经受害的情况下遏制攻击。"),
      residual: bi("Browser or server logs may be incomplete. Overreaction can interrupt study, while underreaction can miss a silent download.", "浏览器或服务器日志可能不完整。反应过度会影响学习，反应不足又可能漏掉静默下载。"),
    },
    {
      id: "password", title: bi("University password entered", "已输入大学账户密码"), context: bi("You submitted your password to the page before recognising the phishing attempt.", "你在识别出网络钓鱼之前向页面提交了密码。"),
      options: [bi("Use the official portal to reset the password, revoke sessions, review MFA, and report immediately", "通过官方门户重置密码、撤销会话、检查 MFA 并立即报告"), bi("Change the password through the same page so the attacker sees only the new one", "通过同一页面修改密码，让攻击者只能看到新密码"), bi("Wait for an unusual-login alert before responding", "等待异常登录提醒后再响应")], answer: 0,
      risks: [bi("This contains both password and session risk while triggering support.", "这能同时控制密码和会话风险，并触发支持。"), bi("Returning to the phishing page gives the attacker more information.", "返回钓鱼页面会向攻击者提供更多信息。"), bi("Attackers may act within minutes and alerts may arrive too late or not at all.", "攻击者可能在几分钟内行动，而提醒可能太晚或根本不会出现。")],
      correctWhy: bi("The password must be treated as compromised, and existing sessions may also need revocation.", "必须将密码视为已经泄露，现有会话也可能需要撤销。"), userNext: bi("Use a known official address, change reused passwords elsewhere, and provide an accurate timeline to support.", "使用已知官方地址，修改其他地方重复使用的密码，并向支持人员提供准确时间线。"), orgNext: bi("Revoke sessions, inspect authentication logs, protect affected services, and assess wider account use.", "撤销会话，检查认证日志，保护受影响服务，并评估更广泛的账户使用情况。"),
      layer: bi("Response and recovery: remove password and session access, investigate account use, and restore a trustworthy identity state.", "响应与恢复：移除密码和会话访问，调查账户使用情况，并恢复可信身份状态。"),
      residual: bi("Password reset alone may leave attacker sessions, mailbox rules, recovery methods, or reused credentials active.", "仅重置密码可能留下攻击者会话、邮箱规则、恢复方式或其他位置重复使用的凭据。"),
    },
    {
      id: "file", title: bi("Suspicious attachment opened", "已打开可疑附件"), context: bi("An unexpected HTML, archive, macro document, or executable was opened.", "意外的 HTML、压缩包、宏文档或可执行文件已经被打开。"),
      options: [bi("Continue working and run a scan later", "继续工作，稍后再扫描"), bi("Stop interacting, disconnect from networks if safe and required by policy, and contact official IT support immediately", "停止操作；如果安全且符合政策要求，断开网络，并立即联系官方 IT 支持"), bi("Delete the original email and attachment to remove the infection", "删除原始邮件和附件以清除感染")], answer: 1,
      risks: [bi("Continued use may allow malware to spread or steal more information.", "继续使用可能让恶意软件传播或窃取更多信息。"), bi("This limits activity while preserving the device and evidence for trained responders.", "这能限制活动，同时为专业响应人员保留设备和证据。"), bi("Deleting the source does not remove executed code and may destroy evidence.", "删除源文件不会清除已经执行的代码，还可能破坏证据。")],
      correctWhy: bi("Possible code execution requires rapid isolation and expert response, not self-investigation.", "可能发生代码执行时，需要迅速隔离并由专业人员响应，而不是自行调查。"), userNext: bi("Describe exactly what was opened and follow support instructions; do not reconnect or power off unless told.", "准确说明打开了什么，并遵循支持指示；除非被告知，否则不要重新联网或关机。"), orgNext: bi("Isolate and examine the endpoint, block indicators, search for related exposure, and recover from a known-clean state.", "隔离并检查终端，阻止指标，搜索相关暴露，并从已知干净状态恢复。"),
      layer: bi("Response and recovery: isolate possible code execution, preserve evidence, determine scope, and rebuild or restore safely.", "响应与恢复：隔离可能的代码执行，保留证据，确认范围，并安全重建或恢复。"),
      residual: bi("Immediate disconnection can limit harm but may interrupt evidence collection or essential study, so local incident policy matters.", "立即断开连接可以限制损害，但也可能影响证据收集或必要学习，因此本地事件政策很重要。"),
    },
    {
      id: "mfa", title: bi("Unknown MFA request approved", "已批准陌生 MFA 请求"), context: bi("MFA was enabled, but you approved a login you did not initiate.", "账户已启用 MFA，但你批准了并非由自己发起的登录。"),
      options: [bi("Assume MFA will block the attacker at the next step", "假设 MFA 会在下一步阻止攻击者"), bi("Use the official service to revoke sessions and secure credentials, deny further prompts, and report immediately", "通过官方服务撤销会话并保护凭据，拒绝后续请求并立即报告"), bi("Approve one more prompt to check whether the first was accidental", "再批准一次，检查第一次是否为意外")], answer: 1,
      risks: [bi("The approval may already have created an authenticated attacker session.", "该批准可能已经为攻击者创建了认证会话。"), bi("This addresses the live session, credentials, and repeated prompt risk.", "这能处理活动会话、凭据和重复推送风险。"), bi("A second approval may grant another session or confirm the attack.", "第二次批准可能授予另一个会话或确认攻击有效。")],
      correctWhy: bi("MFA is a control, not a guarantee; an approved malicious request must be treated as account compromise.", "MFA 是一种控制措施，不是绝对保证；恶意请求被批准后必须按账户入侵处理。"), userNext: bi("Revoke sessions, change credentials if advised, review registered MFA methods, and record the prompt time.", "撤销会话，按指示修改凭据，检查已注册 MFA 方式，并记录推送时间。"), orgNext: bi("Investigate the session and source, revoke tokens, check mailbox rules, and tune MFA protections.", "调查会话和来源，撤销令牌，检查邮箱规则，并调整 MFA 保护。"),
      layer: bi("Detection, response, and recovery: treat the approval as an active session, revoke tokens, and review authentication enrolment.", "发现、响应与恢复：把批准视为活动会话，撤销令牌，并检查认证注册情况。"),
      residual: bi("A stronger MFA method reduces this path, but recovery processes and already-issued sessions remain part of the attack surface.", "更强的 MFA 方式可以减少这条路径，但恢复流程和已经签发的会话仍属于攻击面。"),
    },
    {
      id: "uncertain", title: bi("Message may be genuine", "不确定邮件是否真实"), context: bi("The request matches a plausible university process, but some details feel unusual.", "请求符合某个可能的大学流程，但部分细节感觉异常。"),
      options: [bi("Use an official portal or directory contact that you found independently, without replying or using supplied details", "使用独立找到的官方门户或目录联系方式，不回复，也不使用邮件提供的信息"), bi("Reply and ask a security question", "回复并询问安全问题"), bi("Follow the link but stop if the page asks for a password", "打开链接，但如果页面要求密码就停止")], answer: 0,
      risks: [bi("This tests the claim without trusting any attacker-controlled channel.", "这能在不信任攻击者控制渠道的情况下验证声明。"), bi("An attacker controls the conversation and can provide convincing answers.", "攻击者控制着对话，可以给出看似可信的回答。"), bi("The link itself may expose the browser, collect information, or begin persuasion.", "链接本身可能暴露浏览器、收集信息或开始进一步诱导。")],
      correctWhy: bi("Uncertainty calls for independent verification, not guessing that the message is safe or malicious.", "存在不确定性时应独立核实，而不是猜测信息安全或恶意。"), userNext: bi("Use the known service to check the claim and report the message if it cannot be confirmed.", "使用已知服务检查声明；如果无法确认，则报告该信息。"), orgNext: bi("Make official contact paths easy to find and respond consistently to verification requests.", "让官方联系路径易于查找，并一致地响应核实请求。"),
      layer: bi("Prevention and detection: provide trusted verification routes so uncertainty becomes a controlled check instead of a risky guess.", "预防与发现：提供可信核实路线，让不确定性转化为受控检查，而不是危险猜测。"),
      residual: bi("Verification can delay a legitimate request. Organisations should make the trusted route fast enough that users do not return to the message channel.", "核实可能延迟正常请求。组织应让可信渠道足够快速，减少用户返回邮件渠道的可能。"),
    },
    {
      id: "campaign", title: bi("Organisation-wide phishing campaign", "组织范围的网络钓鱼攻击"), context: bi("Security learns that many users received the same phishing message and some may have interacted.", "安全团队发现许多用户收到相同钓鱼邮件，部分用户可能已经交互。"),
      options: [bi("Send a general reminder telling users to be more careful", "发送一般提醒，要求用户更加小心"), bi("Quarantine matching messages, block indicators, identify exposure, revoke affected access, notify users, and preserve evidence", "隔离匹配邮件，阻止指标，识别暴露，撤销受影响访问，通知用户并保留证据"), bi("Delete all mailboxes containing the subject line", "删除所有包含该主题行的邮箱")], answer: 1,
      risks: [bi("Awareness alone leaves the active campaign, sessions, and exposed accounts untreated.", "仅靠提醒无法处理正在进行的攻击、会话和已暴露账户。"), bi("This combines detection, containment, communication, recovery, and learning.", "这组合了检测、遏制、沟通、恢复和学习。"), bi("Broad deletion is disproportionate, destructive, and removes legitimate mail and evidence.", "大范围删除不成比例且具有破坏性，还会删除合法邮件和证据。")],
      correctWhy: bi("A campaign is a system incident requiring coordinated technical and organisational action.", "攻击活动属于系统事件，需要协调的技术和组织行动。"), userNext: bi("Affected users should report interaction honestly and follow account or device recovery instructions.", "受影响用户应如实报告交互，并遵循账户或设备恢复指示。"), orgNext: bi("Contain the campaign, investigate scope, recover affected identities and devices, communicate clearly, and improve controls.", "遏制攻击、调查范围、恢复受影响身份和设备、清晰沟通并改进控制。"),
      layer: bi("All four layers: prevent more delivery, detect variants and exposure, respond through containment, and recover accounts and devices.", "四个层面共同作用：阻止继续投递，发现变体和暴露，通过遏制进行响应，并恢复账户和设备。"),
      residual: bi("Fast broad action can create false positives or remove evidence; slow action allows further compromise. Scope decisions need logs and review.", "快速大范围行动可能产生误报或移除证据，行动缓慢又会扩大入侵。范围决定需要日志和复核支持。"),
    },
  ],
});
